# .github/stale.yml

# Number of days of inactivity before considering an issue or pull request as stale
daysUntilStale: 60

# Number of days of inactivity before closing a stale issue or pull request
daysUntilClose: 7

# Labels to be added to stale issues or pull requests
labels:
  - stale

# Only consider issues or pull requests with certain labels
onlyLabels:
  - bug
  - enhancement

# Only consider issues or pull requests with specific assignees
onlyAssignees:
  - mister-fix

# Exempt specific issues or pull requests from being marked as stale or closed
exemptLabels:
  - do-not-close
  - exempt-label
  - user-story

# Set to true to ignore issues in a project (defaults to false)
exemptProjects: false

# Set to true to ignore issues in a milestone (defaults to false)
exemptMilestones: false

# Set to true to ignore issues with an assignee (defaults to false)
exemptAssignees: false

# Notify maintainers when an issue or pull request is marked as stale or closed
notifyMaintainers: true

# When to consider a pull request as stale
# Draft PRs can be excluded
# If false, only pull requests marked as "stale" will be considered stale
markDraftPullRequests: false

# Close stale issues and pull requests with a custom comment
closeComment: >
  This issue/pull request has been automatically marked as stale due to
  inactivity. If it is still relevant, please provide an update within the next
  {{ daysUntilClose }} days.

# Reopen issues when they receive new activity
reopenOnActivity: true

# Limit actions to specific branches (optional)
# only:
#   - main
#   - develop

# Limit the number of actions per hour, from 1-30. Default is 30
limitPerRun: 30

repo:
  # Specify the repository where these settings should apply
  owner: mister-fix
  name: taskguardian-api
