name: Lint and Format

# This action works for both pull requests and pushes
on:
  pull_request:
  push:
    branches:
      - main
      - develop

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          # Make sure the actual branch is checked out when running on pull requests
          ref: ${{ github.head_ref }}

      # - name: Set up Node.js
      #   uses: actions/setup-node@v3
      #   with:
      #     node-version: '20' # or your desired Node.js version

      - name: Install dependencies
        run: npm install

      - name: Run ESLint
        run: npm run lint # Ensure 'lint' script is defined in package.json

      - name: Run Prettier
        run: npx prettier --check . # Run Prettier check

